### ISSUE TITLE
Load Failure around Checkpoint Reading 

### ISSUE THREAD

**Issue by paperkettle** [carpedm20/DCGAN-tensorflow#20]
Hi! Bumping into some problems trying to run this. 
If helpful, setup is GTX0180 using Cuda 7.5 with Tensorflow v.8 on Ubuntu 14.04

with my own set I get:

`
 tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
{'batch_size': 64,
 'beta1': 0.5,
 'checkpoint_dir': 'checkpoint',
 'dataset': 'doom2graphics',
 'epoch': 25,
 'image_size': 108,
 'is_crop': False,
 'is_train': True,
 'learning_rate': 0.0002,
 'sample_dir': 'samples',
 'train_size': inf,
 'visualize': False}
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
name: GeForce GTX 1080
major: 6 minor: 1 memoryClockRate (GHz) 1.7335
pciBusID 0000:01:00.0
Total memory: 7.92GiB
Free memory: 6.88GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:755] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0)
 [*] Reading checkpoints...
 [!] Load failed...

`

and then after downloading the celeb set I get: 

`
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
{'batch_size': 64,
 'beta1': 0.5,
 'checkpoint_dir': 'checkpoint',
 'dataset': 'celebA',
 'epoch': 25,
 'image_size': 108,
 'is_crop': True,
 'is_train': True,
 'learning_rate': 0.0002,
 'sample_dir': 'samples',
 'train_size': inf,
 'visualize': False}
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
name: GeForce GTX 1080
major: 6 minor: 1 memoryClockRate (GHz) 1.7335
pciBusID 0000:01:00.0
Total memory: 7.92GiB
Free memory: 6.87GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:755] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0)
 [*] Reading checkpoints...
 [!] Load failed...
F tensorflow/stream_executor/cuda/cuda_dnn.cc:427] could not set cudnn filter descriptor: CUDNN_STATUS_BAD_PARAM
F tensorflow/stream_executor/cuda/cuda_dnn.cc:427] could not set cudnn filter descriptor: CUDNN_STATUS_BAD_PARAM
Aborted (core dumped)

**Comment by carpedm20** [comment]
If you don't have any checkpoint it is failed to load and start training without loading a checkpoint.

I think you're cudnn version is not compatible with the version that TensorFlow uses. You'd better install different cudnn or compile TensorFlow. See https://github.com/tensorflow/tensorflow/issues/1787.

**Comment by LinZhineng** [comment]
This is normal when you first training model， and “Load SUCCESS” if exist "checkpoints"

**Comment by LinZhineng** [comment]
cuda and cudnn installation must follow https://www.tensorflow.org/versions/master/get_started/os_setup.html#optional-install-cuda-gpus-on-linux， and notice version of cuda and cudnn.

**Comment by I-n-d-e-r** [comment]
This is not a problem with miracles. The same problem exists in my case celeb or your own images. However, when mnist works properly as possible. I am using the CPU so you can exclude the previous presumption.

`[inder@dhcppc6 DCGAN-tensorflow] $ python3 main.py --dataset test --is_train True
{'batch_size': 64,
 'beta1': 0.5,
 'checkpoint_dir': 'checkpoint',
 'dataset': 'test',
 'epoch': 25,
 'image_size': 108,
 'is_crop': False,
 'is_train': True,
 'learning_rate': 0.0002,
 'sample_dir': 'samples',
 'train_size': inf,
 'visualize': False}
 [*] Reading checkpoints...
 [!] Load failed...
`

**Comment by WarBean** [comment]
I fix the same problem by checking this line in model.py:

`data = glob(os.path.join("./data", config.dataset, "*.jpg"))`

I turned out that my directory name was not compatible with `config.dataset`. Try to print out the result of this line to make sure that you don't get the `data` as an empty list. Then celebA can run.

**Comment by BLCKPSTV** [comment]
I have this line instead, still I have load failed...

`self.data = glob(os.path.join("./data", self.dataset_name, self.input_fname_pattern))`
