### ISSUE TITLE
tensorflow with gpu 

### ISSUE THREAD

**Issue by vladacar** [carpedm20/DCGAN-tensorflow#209]
I managed to run the package in cpu mode(almost 3 days of rendering), then i uninstalled tensorflow in virtual environment and installed only tensorflow-gpu. now the system won't train the model. are there any instructions how to make this work? i have cuda installed (not in virtual environment though). 
any suggestion would be highly appreciated.
TX

**Comment by Manaswip** [comment]
What is the exact issue? I had 'OOM when allocating tensor issue' when running the model on GPU.  Default data format on GPU is  'NCHW as opposed to default format on CPU which is 'NHWC'. In the code 'NHWC' format is followed because of which model was throwing errors. I changed the code so that "NCHW' format is used and it worked fine.

**Comment by asispatra** [comment]
@vladacar, tensorflow-gpu works with Systems with NVIDIA GPUs e.g. Tesla K80, M40, P100 etc where you needed CUDA. For information, Tensorflow runs on Android also.

**Comment by salmanjan85** [comment]
@asispatra, Need guidance regarding implementation of DCGANs in Tensorflow while i have CPU win 8, 32 bit. Is it possible in CPU?

**Comment by asispatra** [comment]
@salmanjan85, you can try to install "TensorFlow with CPU support only" on your windows system. I think it support on 64-bit system. 
```
C:\> pip3 install --upgrade tensorflow
```
Installation reference: https://www.tensorflow.org/install/install_windows

Please check this issue: https://github.com/tensorflow/tensorflow/issues/384 on "32-bit architecture support?" 

How to build Tensorflow for 32-bit system (as mentioned in the above issue)
http://cudamusing.blogspot.com/2015/11/building-tensorflow-for-jetson-tk1.html


Thanks.

**Comment by salmanjan85** [comment]
Thank you so much for your support. Will try.
Will you be able to help me in implementing DCGANs?



On Sep 19, 2017 10:55 PM, "Asis Patra" <notifications@github.com> wrote:

@salmanjan85 <https://github.com/salmanjan85>, you can try to install
"TensorFlow with CPU support only" on your windows system. I think it
support on 64-bit system.

C:\> pip3 install --upgrade tensorflow

Installation reference: https://www.tensorflow.org/install/install_windows

Please check this issue: tensorflow/tensorflow#384
<https://github.com/tensorflow/tensorflow/issues/384> on "32-bit
architecture support?"

How to build Tensorflow for 32-bit system (as mentioned in the above issue)
http://cudamusing.blogspot.com/2015/11/building-
tensorflow-for-jetson-tk1.html

Thanks.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/carpedm20/DCGAN-tensorflow/issues/209#issuecomment-330619893>,
or mute the thread
